# Generated by Django 4.1.3 on 2022-11-07 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vianda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('Sem', 'Sem'), ('Qui', 'Qui')], default='Sem', max_length=3)),
                ('tipo_menu', models.CharField(choices=[('Nor', 'Nor'), ('Dia', 'Dia'), ('Veg', 'Veg')], default='Sem', max_length=3)),
                ('fecha_inicio_vianda', models.DateField(verbose_name='Fecha Inicio de Vianda')),
                ('cantidad_vianda', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('Pe', 'Pe'), ('Co', 'Co'), ('Ca', 'Ca')], default='Pe', max_length=3)),
                ('item_tipo_plato', models.ManyToManyField(to='vianda.tipoplato')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
