# Generated by Django 4.1.3 on 2022-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vianda', '0002_solicitudvianda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvianda',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudvianda',
            name='frecuencia',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Quincenal', 'Quincenal')], default='Semanal', max_length=9),
        ),
        migrations.AlterField(
            model_name='solicitudvianda',
            name='tipo_menu',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Diabetico', 'Diabetico'), ('Vegetariano', 'Vegetariano')], default='Semanal', max_length=11),
        ),
    ]
